### ISSUE TITLE
still missing something on train.sh after done with labelGeneration.sh

### ISSUE THREAD

**Issue by SeekPoint** [LiyuanLucasLiu/ReHession#2]
bash train.sh 
c_length: 150
l_length: 250
train_file: ./Data/intermediate/KBP/train.data
debug_mode: 2
alpha: 0.025000
test_file: ./Data/intermediate/KBP/test.data
resample: 20
sample: 0.000100
negative: 1
threads: 20
instances: 225977
test_instances: 2111
iters: 20
none_idx: 6
ignore_none: 0
lambda1: 1.000000
lambda2: 1.000000
cv_ratio: 0.100000
error_log: 0
dropout: 0.300000
Starting
Loading training file ./Data/intermediate/KBP/train.data
no such file: ./Data/intermediate/KBP/train.data
c_length: 150
l_length: 250
train_file: ./Data/intermediate/NYT/train.data
debug_mode: 2
alpha: 0.025000
test_file: ./Data/intermediate/NYT/test.data
resample: 20
sample: 0.000100
negative: 1
threads: 20
instances: 530767
test_instances: 3803
iters: 20
none_idx: 0
ignore_none: 0
lambda1: 1.000000
lambda2: 1.000000
cv_ratio: 0.100000
error_log: 0
dropout: 0.300000
Starting
Loading training file ./Data/intermediate/NYT/train.data
no such file: ./Data/intermediate/NYT/train.data

**Comment by LiyuanLucasLiu** [comment]
It seems that the whole ReadMe file is too long to read; therefore, I created a demo file, ```demo_KBP.sh```.
Feel free to try ```bash demo_KBP.sh```
:-)

**Comment by SeekPoint** [comment]
sure, it looks KBP is ready now, but how do it on NYT?
