### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by zhongboyin** [LiyuanLucasLiu/ReHession#3]
您好，请问部署这个项目需要有哪些环境么？

执行bash demo_KBP.sh 时报错：
thon2.7/site-packages/nltk/corpus/util.py", line 81, in __load
    except LookupError: raise e
LookupError: 
**********************************************************************
  Resource u'corpora/wordnet' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/home/bdsirs/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
make: Nothing to be done for `all'.
c_length: 150
l_length: 250
train_file: ./Data/intermediate/KBP/train.data
debug_mode: 2
alpha: 0.025000
test_file: ./Data/intermediate/KBP/test.data
resample: 20
sample: 0.000100
negative: 1
threads: 20
instances: 225977
test_instances: 2111
iters: 20
none_idx: 6
ignore_none: 0
lambda1: 1.000000
lambda2: 1.000000
cv_ratio: 0.100000
error_log: 0
dropout: 0.300000
Starting
Loading training file ./Data/intermediate/KBP/train.data

**Comment by LiyuanLucasLiu** [comment]
我记得不用配复杂的环境（主要是feature extraction 的部分有些环境）

你可以从报错看你哪些没装。比如这次报的错，应该是缺少nltk 的wordnet，你把nltk 装好，然后用nltk 下个wordnet就好
